//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPMNC_Giao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThanhToan()
        {
            this.HoaDon = new HashSet<HoaDon>();
        }
    
        public int MaThanhToan { get; set; }
        public string MaDonHang { get; set; }
        public string PhuongThucThanhToan { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public double TongTien { get; set; }
        public bool TrangThaiThanhToan { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDon { get; set; }
    }
}
